[package]
name = "codeowners"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
clap_derive = "4.1.12"
glob-match = "0.2.1"
itertools = "0.10.5"
jwalk = "0.8.1"
path-clean = "1.0.1"
rayon = "1.7.0"
regex = "1.7.2"
serde = { version = "1.0.158", features = ["derive"] }
serde_yaml = "0.9.19"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

[dev-dependencies]
assert_cmd = "2.0.8"
